---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-demo
  namespace: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: my-container
          imagePullPolicy: Always
          image: marcoliew/my-app:28
          ports:
            - containerPort: 80
