---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: marcoliew/my-app:latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/github-ssh-secret
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: my-app-project
  source:
    repoURL: https://github.com/marcoliew/argocd-manifest.git
    targetRevision: HEAD
    path: env/dev/
  destination:
    server: https://kubernetes.default.svc
    namespace: manifest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
      
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
