apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appkust
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: kust=marcoliew/my-app:latest #alias= cannot be ingored.
    argocd-image-updater.argoproj.io/kust.update-strategy: digest
    argocd-image-updater.argoproj.io/kust.write-back-method: git:secret:argocd/github-ssh-secret-kust
    argocd-image-updater.argoproj.io/kust.git-branch: main
spec:
  project: argocdprj
  source:
    repoURL: ssh://git@github.com/marcoliew/argocd-app-kust.git
    targetRevision: main
    path: env/dev/my-app
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=true
