---
apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:ravindrasinghh/argocd-setup.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACD0y/XxRweozgnqdDKMoCrk/wz2NDsNa0NpmvNMJ9IjggAAAJiF9zSChfc0
    ggAAAAtzc2gtZWQyNTUxOQAAACD0y/XxRweozgnqdDKMoCrk/wz2NDsNa0NpmvNMJ9Ijgg
    AAAEBokanw3M39ESr890kAXiD02hv/dRc4AyeArP3M5NBWF/TL9fFHB6jOCep0MoygKuT/
    DPY0Ow1rQ2ma80wn0iOCAAAAFW1jc1xtbGlhNTEwNUBXSkRGMVFHMw==
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"


# command to generate key
# ssh-keygen -t ed25519 -f ~/.ssh/argocd

